### ISSUE TITLE
Slow on file open. Any mitigations? 

### ISSUE THREAD

**Issue by ColdSauce** [codota/tabnine-vim#1]
Hi, thanks for the great tool. I've noticed that it's pretty slow on startup using both Vim as well as Neovim. 

Is there any way I could run this in an asynchronous manner so that it doesn't block my editor on startup?

**Comment by zxqfl** [comment]
Sorry, I could not reproduce this issue. What platform are you running on? Does the issue always occur or only when opening certain files?

**Comment by ColdSauce** [comment]
Running on MacOS Mojave 10.14. Yeah, always occurs. Even for empty files. If I `ctrl-c` out while it's loading it gives me a YouCompleteMe error. Something's probably just messed up with my vimrc. I'll take a look. Thanks for the help!

**Comment by ryuheechul** [comment]
I'm also experiencing the slow start up with the plugin installed and here is my data.

without this plugin, just 1ms on VimEnter resulting total 255ms with my other setup
```
times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines
...
245.623  001.512: VimEnter autocommands
255.057  009.429: first screen update
```

with this plugin, just 451ms on VimEnter resulting total 717ms with my other setup
```
times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines
...
704.616  451.371: VimEnter autocommands
717.963  013.335: first screen update
```
 
quite a noticeable difference observed.

**Comment by ryuheechul** [comment]
Just found a workaround in case of using [Packer](https://github.com/wbthomason/packer.nvim)

```lua
use { 'codota/tabnine-vim', event = 'InsertEnter' }
```

This makes the plugin to be loaded only after `InsertEnter` event so that it doesn't slow down start up time.

You might need to run `:PackerSync` to take effect.
