### ISSUE TITLE
Support for vim-lsp completion engine

### ISSUE THREAD

**Issue by 0xDagal** [codota/tabnine-vim#100]
- OS version: GNU+Linux Manjaro	
 - Editor version (Output of `vim --version`): VIM - Vi IMproved 8.2
 
TabNine has a lot of support and I am really happy that it plugs with multiple completion engines for VIM (YCM, deoplete, CoC...) but I know that it works by LSP so I would like a support for [vim-lsp](https://github.com/prabirshrestha/vim-lsp) with, why not, [vim-lsp-settings](https://github.com/mattn/vim-lsp-settings) for an easy installation.

Maybe I just do not know something about how LSP works and TabNine can already be used with vim-lsp by now, excuse me if it is the case. 

gz#9058

**Comment by maya-tabnine** [comment]
Hi, I think that’s a good idea!
We’re not supporting it at the moment, but I’ll pitch it to the team and see what they think about adding it.
Thanks :)

**Comment by wuilliam321** [comment]
Hi! this will be great! I'm lsp user :)

**Comment by jayli** [comment]
You can try [vim-easycomplete](https://github.com/jayli/vim-easycomplete). It's very easy to install in vim/nvim just like vim-lsp.

**Comment by 0xDagal** [comment]
Seems promising be sure that I'll give it a try @jayli :smiley:
