### ISSUE TITLE
Tabnine for Netbeans

### ISSUE THREAD

**Issue by kmagwenzi** [codota/tabnine-vim#102]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor version (Output of `vim --version`):
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version(Type `TabNine::version` in insert mode):
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

**Issue Details:**

gz#9778

**Comment by maya-tabnine** [comment]
Hi!
While we do our best to reach every possible IDE on the planet, there is a vast amount of such, forcing us to select a few.
There is a repository to grasp the possible amount of interest in such plugin: https://github.com/tabnine/tabnine-netbeans-ide
If we'd see enough interest from the community, we will make sure such a plugin exists.

Also, if it interests you, you can develop such a plugin yourself. Here is the guide: https://github.com/codota/TabNine/blob/master/HowToWriteAClient.md
