### ISSUE TITLE
Broken on python 3.10

### ISSUE THREAD

**Issue by WiSaGaN** [codota/tabnine-vim#103]
- Fedora 35	
 - Editor version (Output of `vim --version`):
     > VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 07 2021 00:00:00)
Included patches: 1-3755
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl/dyn          +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3/dyn       +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby/dyn          +wildmenu
+cursorbind        +lua/dyn           +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      +sodium            -xfontset
+digraphs          +mouse             -sound             -xim
-dnd               -mouseshape        +spell             -xpm
-ebcdic            +mouse_dec         +startuptime       -xsmp
+emacs_tags        +mouse_gpm         +statusline        -xterm_clipboard
+eval              -mouse_jsbterm     -sun_workshop      -xterm_save
+ex_extra          +mouse_netterm     +syntax            
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -DSYS_VIMRC_FILE=/etc/vimrc -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L. -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -L/usr/local/lib -o vim -lm -lselinux -lncurses -lsodium -lacl -lattr -lgpm -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fstack-protector-strong -L/usr/local/lib -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -ldl -lm -lcrypt -lutil -lc 

**Issue Details:**
After upgrade to Fedora 35, opening `vim` results in below error in status line:
```
YouCompleteMe unavailable: module 'collections' has no attribute 'Mapping'
```
I suspect it is because Fedora 35 upgrades Python from 3.9 to 3.10
I can't seem to get TabNine::config running in vim.

gz#9894

**Comment by bilucodota** [comment]
did you try our new fork? https://github.com/tabnine/YouCompleteMe

**Comment by WiSaGaN** [comment]
> did you try our new fork? https://github.com/tabnine/YouCompleteMe

No. Can you elaborate why that is relavent to this issue?

**Comment by bilucodota** [comment]
The new fork is updated more frequently and thus expected to work better on newer installations.

**Comment by luoleicn** [comment]
> > did you try our new fork? https://github.com/tabnine/YouCompleteMe
> 
> No. Can you elaborate why that is relavent to this issue?

have you solved this problem?

**Comment by bilucodota** [comment]
@WiSaGaN @luoleicn we've added python3 support on this branch: https://github.com/codota/tabnine-vim/tree/python3

**Comment by WiSaGaN** [comment]
Thanks @bilucodota . This now works for me. Please feel free to close this when you see fit.

**Comment by bilucodota** [comment]
Keep us posted!

**Comment by luoleicn** [comment]
@bilucodota Thank you, but python3 branch doesnot work either, still "YouCompleteMe unavailable: module 'collections' has no attribute 'Mapping'"

**Comment by luoleicn** [comment]
and my evn is Python 3.7.3, VIM - Vi IMproved 8.2, macOS 12.1

**Comment by bilucodota** [comment]
Hi @luoleicn can you share the status of `git show` as well as the output of `:messages` ?
One again - I would definitely recommend that you switch to our latest  YCM fork https://github.com/tabnine/YouCompleteMe

**Comment by luoleicn** [comment]
@bilucodota thanks, I moved to https://github.com/tabnine/YouCompleteMe, but still not working:(, :message said:

The ycmd server SHUT DOWN (restart with ':YcmRestartServer'). Unexpected exit code -6. Type ':YcmToggleLogs ycmd_60335_stderr_3zwquq7b.log' to check th

I check ycmd_60335_stderr_3zwquq7b.log 
No global extra conf, not calling method YcmCorePreload

**Comment by bilucodota** [comment]
did you follow the installation instructions? https://github.com/tabnine/YouCompleteMe#installation

**Comment by luoleicn** [comment]
@bilucodota  Thanks again,  I change my default python from miniconda3 to homebrew, it works for me now, although i dont know why

**Comment by bilucodota** [comment]
great!

**Comment by schrotie** [comment]
Hi @bilucodota , I just ran into the same problem, apparently after my Manjaro (arch) updated python.
python: 3.10.1
vim:  8.2.4106

I'm not using pathogen, vundle or some such thing but the built-in native package loading of vim 8.

As recommended here I installed  https://github.com/tabnine/YouCompleteMe (in ~/.vim/pack/schrotie/start/YouCompleteMe and did _python3 install.py --all_ there) successfully.

I also switched ~/.vim/pack/schrotie/start/tabnine-vim to the python3 branch. I tried calling the install script there. _install.sh_ says it's deprecated and complains that urllib3 is missing (which is installed). _python3 install.py_ fails with:
```
Traceback (most recent call last):
  File "/home/schrotie/.vim/pack/schrotie/start/tabnine-vim/third_party/ycmd/build.py", line 50, in <module>
    import requests
  File "/home/schrotie/.vim/pack/schrotie/start/tabnine-vim/third_party/ycmd/third_party/requests/requests/__init__.py", line 134, in <module>
    from . import packages
ImportError: bad magic number in 'requests.packages': b'\x03\xf3\r\n'
```

When I then start vim I get a ton of errors. However, I'm not sure if it prints all problems ... there's quite some traces. Some are:
```
AttributeError: type object 'BaseRequest' has no attribute 'session'. Did you mean: 'Session'?
ImportError: bad magic number in 'requests.packages': [...]
E858: Eval did not return a valid python object
```
Do you have any suggestions?

**Comment by schrotie** [comment]
The issue was solved for me by bilucodata. See [issue 107](https://github.com/codota/tabnine-vim/issues/107).
