### ISSUE TITLE
Add the `coq_nvim` completion engine

### ISSUE THREAD

**Issue by ofk-enterprise-account** [codota/tabnine-vim#104]
The `Coq Nvim` completion engine ([here](https://github.com/ms-jpq/coq_nvim)) is a great completion engine, very fast, very powerful, very useful, and integrates completely with NeoVim's builtin LSP server.

Adding TabNine mojo to its already great output would take it to the next level.

gz#10542

**Comment by bilucodota** [comment]
Hi @ofk-enterprise-account, thanks for reaching out!

To be honest, I wasn't familiar with `coq_nvim` - but according to their documentation - it seems like is already integrated with Tabnine, it's just disabled by default 
https://github.com/ms-jpq/coq_nvim#tabnine

**Comment by ofk-enterprise-account** [comment]
Oh wow, that's cool.
I hope (s)he doesn't drop support of you.

Thanks.
I'll close this ticket now.
