### ISSUE TITLE
Support for ALE?

### ISSUE THREAD

**Issue by robacarp** [codota/tabnine-vim#105]
I'm actually not sure if [ALE](https://github.com/dense-analysis/ale) provides the LSP hooks tabnine needs. I was able to switch from ALE over to coc, but my experience with coc hasn't been wonderful. If ALE can do it, the best feature of ALE is that it doesn't need a plugin for _most_ languages, it just looks to see what the native tooling for the language is and uses that if it's there. Perhaps a tabnine integration would be lightweight as a result.

gz#10885

**Comment by bilucodota** [comment]
Hi @robacarp 
Thanks for reaching out.

Bot ALE and Tabnine are integrated with Deoplete. I haven't tested it myself, but this could possibly meet your needs?

**Comment by bilucodota** [comment]
Marking this as closed for now. Let me know if you have further questions.
