### ISSUE TITLE
Vim-Easycomplete support TabNine

### ISSUE THREAD

**Issue by jayli** [codota/tabnine-vim#109]
- OS version: Mac + Linux	
 - Editor version (Output of `vim --version`): vim 8.x and neovim 0.5.0~0.7.0
 - Programming language: ts/go/python/vim script/lua/...
 - TabNine extension version(Type `TabNine::version` in insert mode): 4.1.3
 
TabNine is very cool. I use vim and neovim. So I need a plugin compatible in both. There are no ready-made plugins. Therefor I developed a plugin([vim-easycomplete](https://github.com/jayli/vim-easycomplete)) myself. In this plugin, TabNine is very easy to install and use. For now this vim plugin is widely used in my team.  

lsp user may like it.

So

I want to thank you for developing such a great tool.

**Comment by bilucodota** [comment]
@jayli THANKS for supporting the community. 
Could you please drop us a message at support@tabnine.com and mention this thread? 
We would love to send you some Tabnine swag.

**Comment by jayli** [comment]
> @jayli THANKS for supporting the community. Could you please drop us a message at [support@tabnine.com](mailto:support@tabnine.com) and mention this thread? We would love to send you some Tabnine swag.

I've send a email to you!~
