### ISSUE TITLE
Vim option to disable promotional message

### ISSUE THREAD

**Issue by oxinabox** [codota/tabnine-vim#11]
[The FAQ says](https://tabnine.com/faq)

> I don't like the message in the autocomplete popup telling me that I can upgrade to index more files.
>
> You can disable it by typing `TabNine::hide_promotional_message`. The popup only exists to ensure users are aware the paid version exists.

It would be great to have an option to do this via a setting in my vimrc
Since when running from VIM I have nowhere to type that command.
And when I run it in the vim command bar, it jsut gives an invalid command error

**Comment by zxqfl** [comment]
You can enter insert mode and type it into the file. Leaving this open as it would be nice to support the other method as well.

**Comment by oxinabox** [comment]
Alternatively, if there was an enviroment variable for it, that would work too.
