### ISSUE TITLE
 +79143115346

### ISSUE THREAD

**Issue by YK15051984** [codota/tabnine-vim#112]
ublic Phonemetadata.PhoneNumberDesc setNationalNumber+9143115346Pattern+7(java.lang.String **please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor version (Output of `vim --version`):
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version(Type `TabNine::version` in insert mode):
 public boolean [hasNationalNumberPattern](+7)9143115346
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.
com.google.i18n.phonenumbers.Phonemetadata.PhoneMetadataCollection.Builder

**Issue Details:**

gz#14391

**Comment by maya-tabnine** [comment]
How can I help?
