### ISSUE TITLE
My Config

### ISSUE THREAD

**Issue by TechDeveloperProgrammer** [codota/tabnine-vim#113]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor version (Output of `vim --version`):
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version(Type `TabNine::version` in insert mode):
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

**Issue Details:**

gz#14409

**Comment by TechDeveloperProgrammer** [comment]
Ok

**Comment by maya-tabnine** [comment]
How can I help you?
