### ISSUE TITLE
spyder

### ISSUE THREAD

**Issue by erty34yugeq37** [codota/tabnine-vim#116]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	win
 - Editor version (Output of `vim --version`):   
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version(Type `TabNine::version` in insert mode):
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

**Issue Details:**

gz#18570

**Comment by maya-tabnine** [comment]
Hi! How can I help?

**Comment by amirbilu** [comment]
Hi erty34yugeq37,

We haven't heard back from you in a while.

Would you please let me know if you still need my assistance?

Thank you,

Robbie Flores
Tabnine Support
<br><p><em><small>°°°</small></em></p>

**Comment by erty34yugeq37** [comment]
No sorry it was just the plugin wasn't possible for Spyder but I fixed it
so no worries love and kisses the one and only not anti anything crusader
