### ISSUE TITLE
[coc.nvim] Download error Invalid response from https://update.tabnine.com/bundles/4.4.276/aarch64-unknown-linux-musl/TabNine.zip: 403

### ISSUE THREAD

**Issue by wacdev** [codota/tabnine-vim#119]
[coc.nvim] Download error Invalid response from https://update.tabnine.com/bundles/4.4.276/aarch64-unknown-linux-musl/TabNine.zip: 403

gz#22723<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/22723'>Zendesk ticket #22723</a>)</i>

**Comment by TzufTabnine** [comment]
@wacdev Did you try to download Tabnine from [here](https://github.com/codota/tabnine-vim)?
Also, try this [link](https://update.tabnine.com/bundles/4.4.276/x86_64-unknown-linux-musl/TabNine.zip)
