### ISSUE TITLE
Error executing vim.schedule lua callback: ...are/nvim/plugged/tabnine-nvim/lua/tabnine/completion.lua:12: attempt to get length of field 'results' (a nil value) 

### ISSUE THREAD

**Issue by allan-simon** [codota/tabnine-vim#120]
**please complete the following information:**	
 - OS version: Ubuntu 
 - Editor version (Output of `vim --version`):
 
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

 - Programming language: [e.g. js, ts, c++]	: `php`
 - TabNine extension version(Type `TabNine::version` in insert mode): 4.9.0
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

from times to times I got the following error

```
Error executing vim.schedule lua callback: ...are/nvim/plugged/tabnine-nvim/lua/tabnine/completion.lua:12: attempt to get length of field 'results' (a nil value)                    
stack traceback:
        ...are/nvim/plugged/tabnine-nvim/lua/tabnine/completion.lua:12: in function 'valid_response'
        ...are/nvim/plugged/tabnine-nvim/lua/tabnine/completion.lua:69: in function 'callback'
        ...l/share/nvim/plugged/tabnine-nvim/lua/tabnine/binary.lua:89: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

gz#26513<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/26513'>Zendesk ticket #26513</a>)</i>

**Comment by amirbilu** [comment]
Hi @allan-simon please move this to https://github.com/codota/tabnine-nvim/issues

**Comment by allan-simon** [comment]
Thanks I will move it, but is it not possible in github to move issue from one project to an other as a maintainer ?  (I don't know github enough but it is with gitlab )
