### ISSUE TITLE
[NVIM] 100% CPU for long periods

### ISSUE THREAD

**Issue by deevus** [codota/tabnine-vim#14]
From htop:
![image](https://user-images.githubusercontent.com/856194/49837492-a19ef280-fdfa-11e8-8be6-fcdc5924a7ed.png)

OS: Fedora 29
Editor: NVIM v0.3.1

What other info do you need?

**Comment by zxqfl** [comment]
Thanks for the report. Does this occur in an open source project? This would help me reproduce the issue. It seems like this might be the same issue as https://github.com/zxqfl/TabNine/issues/24.

**Comment by deevus** [comment]
I'd have to check.

**Comment by deevus** [comment]
Even with deoplete-tabnine this still persists. So it's probably related to the TabNine binary as you say

**Comment by jokeyrhyme** [comment]
I just encountered this in the last week or so, and it's happening right now as I type this

My whole computer froze for several minutes, `top` is showing TabNine "winning" by using 99% CPU (occasionally, `rls` (Rust) will rise from insignificant to 2nd place), the hard drive light is on solid (not flickering), `/proc/loadavg` went as high as 19.5

After several minutes, my system regained interactivity / responsiveness, so I could check `top`, etc

Previously, when this happened, I just reset my computer, but this time I was patient, and it paid off :)

- nvim 0.3.7
- python 3.7.3
- pynvim 0.3.2
- ~/.vim/plugged/tabnine-vim b9f7b52e8d42f868c31399f92783b721b5851363
- `/proc/version` Linux version 5.1.7-arch1-1-ARCH (builduser@heftig-7095) (gcc version 8.3.0 (GCC)) #1 SMP PREEMPT Tue Jun 4 15:47:45 UTC 2019
