### ISSUE TITLE
Omnicomplete eagerly completing after 2 characters

### ISSUE THREAD

**Issue by deevus** [codota/tabnine-vim#16]
I just updated TabNine to the latest version

Expected: While typing, TabNine suggests autocompletions and I can select them myself

Actual: If I type two characters and TabNine has available autocompletions, it picks the first one and completes the phrase for me. 

I had to disable TabNine to continue working. Hoping that this presents simply and isn't some complex interaction between multiple plugins.

**Comment by deevus** [comment]
This also happened on my Windows machine. I had to disable TabNine there too.

**Comment by deevus** [comment]
If this isn't going to get fixed can I get a refund?

**Comment by zxqfl** [comment]
Sorry for the late reply. You can get a refund, just send me an email at jacob@jacobjackson.com. You could also try the Deoplete client: https://github.com/tbodt/deoplete-tabnine

**Comment by zxqfl** [comment]
I'd also be grateful if you could post your .vimrc as I can't reproduce this on my local machine.

**Comment by deevus** [comment]
https://github.com/deevus/dotfiles/tree/10186805924bcd8990bd1326905135825c69772c/.config/nvim

**Comment by deevus** [comment]
`deoplete-tabnine` seems to be working.

**Comment by deevus** [comment]
I don't actually want to get a refund. My preference is to use TabNine :+1:
