### ISSUE TITLE
Clarify on website that tabnine.vim is adapted from YCM

### ISSUE THREAD

**Issue by theodcr** [codota/tabnine-vim#2]
First thanks for this great tool!

The website tabnine.com doesn't mention that YouCompleteMe installation instructions should be followed in order to install this plugin. This only becomes clear when landing on this repo.

So at first TabNine didn't "work as soon as I installed it" following only the instructions on tabnine.com ;-)

**Comment by zxqfl** [comment]
Sorry about that. What error do you get when you don't run `install.py`?

**Comment by dharmab** [comment]
There's no error; completion silently doesn't function.

**Comment by ggerganov** [comment]
Does this mean I cannot use both YCM and TabNine? I already had YCM installed, and installing TabNine does not change the way auto completion works. I am also missing TabNine::* commands (which I understand from other issues can be triggered by typing in Insert mode).

**Comment by zxqfl** [comment]
Can you try removing YCM from your .vimrc?

**Comment by ggerganov** [comment]
Yes, commenting the YCM stuff in my .vimrc file makes TabNine work. Thanks!

**Comment by jtr860830** [comment]
So, YCM and TabNine can't work together ?

**Comment by zxqfl** [comment]
That's correct.

**Comment by mrquincle** [comment]
If you use `Vundle`, after commenting YCM you will have to actually remove it. 

In your `~/.vimrc`:

```
" Plugin 'Valloric/YouCompleteMe
```

Then in vim itself: 

```
:PluginClean
```

After this, tabnine will do the completions rather than ycm.
