### ISSUE TITLE
tabnine breaks FuzzyFinder's matcher

### ISSUE THREAD

**Issue by wolever** [codota/tabnine-vim#23]
# Issue Prelude

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x] I have read and understood YCM's [CONTRIBUTING][cont] document.
- [x] I have read and understood YCM's [CODE_OF_CONDUCT][code] document.
- [x] I have read and understood YCM's [README][readme], **especially the
  [Frequently Asked Questions][faq] section.**
- [x] I have searched YCM's issue tracker to find issues similar to the one I'm
  about to report and couldn't find an answer to my problem. ([Example Google
  search.][search])
- [x] If filing a bug report, I have included the output of `vim --version`.
- [x] If filing a bug report, I have included the output of `:YcmDebugInfo`.
- [x] If filing a bug report, I have attached the contents of the logfiles using
  the `:YcmToggleLogs` command.
- [x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [x] If filing a bug report, I have included a minimal test case that reproduces
  my issue, including what I expected to happen and what actually happened.
- [x] If filing a installation failure report, I have included the entire output
  of `install.py` (or `cmake`/`make`/`ninja`) including its invocation
- [x] **I understand this is an open-source project staffed by volunteers and
  that any help I receive is a selfless, heartfelt _gift_ of their free time. I
  know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

Thank you for adhering to this process! It ensures your issue is resolved
quickly and that neither your nor our time is needlessly wasted.

# Issue Details

When using with FuzzyFinder, TabNine interferes with FuzzyFinder completion.

* What did you do?

To reproduce:

1. Install FuzzyFinder: `Plug 'vim-scripts/FuzzyFinder'`

2. Trigger FuzzyFinder: `:FufFile`

3. Type a letter

4. Notice that the FuzzyFinder list blinks open, then is replaced by the tabnine popup, then everything disappears.

Video: https://www.screencast.com/t/vth6eMEWuwxO

* What did you expect to happen?

TabNine should not activate when FuzzyFinder is active.

# Diagnostic data

## Output of `vim --version`

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 11 2019 08:22:43)
macOS version
Included patches: 1-1517```

## Output of `YcmDebugInfo`

```
Printing YouCompleteMe debug information...
-- Client logfile: /var/folders/11/cx101t9n7yb_rf6fk58_8swm0000gp/T/ycm_ZGiRxE.log
-- Server errored, no debug info from server
-- Server running at: http://127.0.0.1:50059
-- Server process ID: 44491
-- Server logfiles:
--   /var/folders/11/cx101t9n7yb_rf6fk58_8swm0000gp/T/ycmd_50059_stdout_CLUP0m.log
--   /var/folders/11/cx101t9n7yb_rf6fk58_8swm0000gp/T/ycmd_50059_stderr_OINJb7.log```

## Contents of YCM, ycmd and completion engine logfiles

Log files are empty except for `ycm_*.log`, which contains:

```
2019-07-18 14:04:37,397 - ERROR - Error while handling server response
Traceback (most recent call last):
  File "/Users/wolever/.config/vim/plug/tabnine-vim/autoload/../python/ycm/client/base_request.py", line 79, in HandleFuture
    return _JsonFromFuture( future )
  File "/Users/wolever/.config/vim/plug/tabnine-vim/autoload/../python/ycm/client/base_request.py", line 247, in _JsonFromFuture
    response.raise_for_status()
  File "/Users/wolever/.config/vim/plug/tabnine-vim/third_party/ycmd/third_party/requests/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:50374/debug_info
```

## OS version, distribution, etc.

macOS 10.14.5, both command-line vim and MacVim.

**Comment by bfulop** [comment]
I have a very similar issue. I'm using Neovim and the [nvim-telescope plugin](https://github.com/nvim-telescope/telescope.nvim). 
Tabnine-vim tries to autocomplete the search terms I enter in Telescope.

**Comment by joehannes** [comment]
I got the same issue with nvim-telescope plus tabnine and compe-tabnine;
Actually it's worse, often I simply hit enter when I got the right thing in my fuzzy-finder and tabnine silently pastes and also overwrites parts of code where the cursor was before ...
Example: I use telescope to open a file, tabnine pastes and overwrites parts in the old file while the new file is opened ..
It even took me some time to spot this issue, it was and is really annoying

**Comment by joehannes** [comment]
I managed to find my error and solve my issue: I had codota/tabnine installed. after not being able to find how to configure autocompletion, I installed compe-tabnine alongside it. now compe actually does respect telescope and doesn't trigger autocompletion in any way, but since I had both packages installed (which I thought was necessary, but ... that's not so) I couldn't see that codota/tabnine was still triggering while compe-tabnine didn't through the compe integration :)

-> I simply had to remove codota/tabnine because compe-tabnine would download and install tabnine on its own
-> oops, also: compe-tabnine might not succeed in installing tabnine - I had to navigate to the package folder and manually trigger install.sh like twice or so ... then it finally worked
