### ISSUE TITLE
Support some YCM's options

### ISSUE THREAD

**Issue by yous** [codota/tabnine-vim#3]
YCM has quite many global options, and you can see them on `doc/youcompleteme.txt`, `:help youcompleteme-options`. Of course many of them are not relevant to or can't be applied to TabNine, but yet the plugin is a fork of YCM, and I think some of them can be handled by plugin itself.

For example:
``` vim
let g:ycm_min_num_of_chars_for_completion = 4
let g:ycm_filetype_blacklist = {
      \ 'diff': 1,
      \ 'infolog': 1,
      \ 'mail': 1,
      \ 'markdown': 1,
      \ 'netrw': 1,
      \ 'notes': 1,
      \ 'pandoc': 1,
      \ 'qf': 1,
      \ 'tagbar': 1,
      \ 'text': 1,
      \ 'unite': 1,
      \ 'vimwiki': 1 }
```

It seems that `g:ycm_filetype_blacklist` and `g:ycm_filetype_whitelist` can be handled by fixing [`s:AllowedToCompleteInBuffer()`](https://github.com/zxqfl/tabnine-vim/blob/7b13716b661acee68a3444ac972a5f6b15e70dcf/autoload/youcompleteme.vim#L393), but `g:ycm_min_num_of_chars_for_completion` is read by [ycmd](https://github.com/zxqfl/tabnine-vim/blob/7b13716b661acee68a3444ac972a5f6b15e70dcf/third_party/ycmd/ycmd/completers/completer.py#L171).

**Comment by dmd** [comment]
Related? Is there a way to have tabnine start suggesting only after tab is pressed, rather than always displaying?

**Comment by anowlcalledjosh** [comment]
Thanks for the pointer to `s:AllowedToCompleteInBuffer()`; removing the `return 1` from the top of that function apparently makes the filetype blacklist just work, I don't know why that was added in the first place, and the commit message (9b868b9c178c820539fe7cbb50c87d1121599f2a) isn't helpful.
