### ISSUE TITLE
Only YouCompleteMe portion of TabNine working

### ISSUE THREAD

**Issue by newtonchris** [codota/tabnine-vim#32]
# Issue Prelude

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [X ] I have read and understood YCM's [CONTRIBUTING][cont] document.
- [X ] I have read and understood YCM's [CODE_OF_CONDUCT][code] document.
- [ X] I have read and understood YCM's [README][readme], **especially the
  [Frequently Asked Questions][faq] section.**
- [ X] I have searched YCM's issue tracker to find issues similar to the one I'm
  about to report and couldn't find an answer to my problem. ([Example Google
  search.][search])
- [X ] If filing a bug report, I have included the output of `vim --version`.
- [X ] If filing a bug report, I have included the output of `:YcmDebugInfo`.
This is for TabNine not YCM
- [X ] If filing a bug report, I have attached the contents of the logfiles using
  the `:YcmToggleLogs` command.
- [ X] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [ X] If filing a bug report, I have included a minimal test case that reproduces
  my issue, including what I expected to happen and what actually happened.
- [X ] If filing a installation failure report, I have included the entire output
  of `install.py` (or `cmake`/`make`/`ninja`) including its invocation
- [X ] **I understand this is an open-source project staffed by volunteers and
  that any help I receive is a selfless, heartfelt _gift_ of their free time. I
  know I am not entitled to anything and will be polite and courteous.**
- [ X] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

Thank you for adhering to this process! It ensures your issue is resolved
quickly and that neither your nor our time is needlessly wasted.

# Issue Details

> Provide a clear description of the problem, including the following key
> questions:

* What did you do?
Installed TabNine with a valid key.
When I type:
TabNine::version I see 2.0.4
When I type:
TabNine::sem I see "Semantic completion enabled"
All I see is what appears to be the normal python YouCompleteMe autocomplete and not the TabNine actual code based autocomplete.
I have tried to uninstall everything and reinstall.  
I have also tried to remove all plugins except the Vundle and the tabnine-vim.  
This is running on macvim under High-Sierra.
When I type:
:PluginList I see the tabnine in the list of installed plugins.

> Include steps to reproduce here.

> Include description of a minimal test case, including any actual code required
> to reproduce the issue.

* What did you expect to happen?

> Include description of the expected behaviour.

* What actually happened?

> Include description of the observed behaviour, including actual output,
> screenshots, etc.

# Diagnostic data

## Output of `vim --version`
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 21 2019 22:55:21)
macOS version
Included patches: 1-1722
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       +tcl
+arabic            +find_in_path      +mouse_xterm       +termguicolors
+autocmd           +float             +multi_byte        +terminal
+autochdir         +folding           +multi_lang        +terminfo
-autoservername    -footer            -mzscheme          +termresponse
+balloon_eval      +fork()            +netbeans_intg     +textobjects
+balloon_eval_term +fullscreen        +num64             +textprop
+browse            -gettext           +odbeditor         +timers
++builtin_terms    -hangul_input      +packages          +title
+byte_offset       +iconv             +path_extra        +toolbar
+channel           +insert_expand     +perl              +transparency
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       -X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        -xsmp
+emacs_tags        -mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
-farsi             -mouse_sysmouse    -tag_any_white     
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby    

> Place the output here, or a link to a [gist][].

## Output of `YcmDebugInfo`

> Place the output here, or a link to a [gist][].

## Contents of YCM, ycmd and completion engine logfiles

> Add `let g:ycm_log_level = 'debug'` to vimrc, restart Vim, reproduce the
> issue, and include link here to a [gist][] containing the entire logfiles for
> ycm, ycmd and any completer logfiles listed by `:YcmToggleLogs`.

## OS version, distribution, etc.

> Include system information here.

## Output of build/install commands

> Include link to a [gist][] containing the invocation and entire output of
> `install.py` if reporting an installation issue.

[cont]: https://github.com/Valloric/YouCompleteMe/blob/master/CONTRIBUTING.md
[code]: https://github.com/Valloric/YouCompleteMe/blob/master/CODE_OF_CONDUCT.md
[readme]: https://github.com/Valloric/YouCompleteMe/blob/master/README.md
[faq]: https://github.com/Valloric/YouCompleteMe/blob/master/README.md#faq
[search]: https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fgithub.com%2FValloric%2FYouCompleteMe%2Fissues%20python%20mac
[gist]: https://gist.github.com/

Thank you.

**Comment by 4dplanner** [comment]
I've been having a similar issue - YouCompleteMe results seem to override TabNine. A (n irritating) workaround for this is pressing backspace, which will cause the TabNine menu to pop up once more.

**Comment by newtonchris** [comment]
Thank you for the response.  The backspace workaround does not seem to work for me.
