### ISSUE TITLE
Heavy memory usage

### ISSUE THREAD

**Issue by dalizard** [codota/tabnine-vim#37]
# Issue Prelude
I am running this on:
- 2015 MacBook Pro i7@2.5 16GB RAM, macOS Mojave 10.14.6
- nvim 0.3.8
- Paid TabNine 2.1.14

# Issue Details
- Start-up time is significantly impacted by tabnine-vim
- Memory usage is high

## What did you do?
- Deleted any previous models
- Measured the startup time of nvim with and without the tabnine-vim plugin
- Measured the memory usage after starting nvim inside the just-cloned [sinatra](https://github.com/sinatra/sinatra) repository; no other nvim instance running

## What did you expect to happen?
- The startup time not to be significantly impacted
- The memory usage not be that high

## What actually happened?
- [Startup time](https://gist.github.com/dalizard/25248d6a4a3243fe876a18242f61a39b) without tabnine-vim
- [Startup time](https://gist.github.com/dalizard/eb11631b63b110b85d245c32b23f1264) with tabnine-vim
- Memory usage is 1.67GB for a single nvim instance running TabNine Local:
```bash
~ $ ps -p 9915 -o %cpu,%mem,rss
 %CPU %MEM    RSS
  0.0 10.5 1757228
```
- TabNine config:
```json
{
  "version": "1.0.9",
  "hide_promotional_message": false,
  "beta_enabled": "No",
  "ignore_all_lsp": true,
  "creation_time": "2019-08-20T06:58:01.422686Z",
  "semantic_status": {
    "html": "Enabled",
    "go": "Enabled",
    "ruby": "Enabled",
    "javascript": "Enabled"
  },
  "disable_auto_update": false,
  "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": false,
  "hosted_deep_completions_enabled": "Disabled",
  "tabnine_cloud_host": null,
  "tabnine_cloud_port": null,
  "cloud_whitelist": [],
  "api_key": null,
  "api_key_service_level": null,
  "api_base_url": null,
  "local_enabled": "Yes",
  "disable_local_when_using_battery": false,
  "hide_deep_information_message": false,
  "enable_power_saving_mode": false,
  "rate_limit_interval_seconds": null,
  "rate_limit_amount": null
}
```

**Comment by crypdick** [comment]
I'm seeing RAM usage of 2.2GB.

**Comment by sebaspasker** [comment]
Is there any way to limit the maximum amount of ram use of tabnine?
