### ISSUE TITLE
Config files location

### ISSUE THREAD

**Issue by dagadbm** [codota/tabnine-vim#43]
I see no TabNine command on vim to use.
How can I find where the config files are?
Do they depend per editor (folder for vim, for vscode , etc) or do they all share the same config?
this is not that well documented IMO.

**Comment by uolot** [comment]
There's no command, you need to type `TabNine::something` directly into a buffer in insert mode.
On Linux the config file is in `$HOME/.config/TabNine/`, but you can also use `TabNine::config` which opens a new web browser window with config panel.

**Comment by s-a-barnett** [comment]
If I'm trying to activate Tabnine Pro for Vim, which files in `$HOME/.config/TabNine/` do I need to edit? How can I edit them? I can't get a web browser window to open with `TabNine::config` since I'm SSH'ing into a remote server.
