### ISSUE TITLE
Completion stops in neovim after a while

### ISSUE THREAD

**Issue by jc00ke** [codota/tabnine-vim#44]
I'm not sure how to repro it exactly, but after some time `TabNine` and/or `YCM` will stop autocompleting until I restart. I'm not even able to `TabNine::version` in this scenario.

I'm running an activated version `2.1.17` with Neovim `0.3.4`. I think I've seen an error message relating to `YCM`, will try to grab a screencap if I see it again.

Are there logs I can turn on?

One odd thing I found is that the version reported in `~/.config/TabNine/tabnine_config.json` is different than what I see in the config server:

![image](https://user-images.githubusercontent.com/18191/66086014-af5b6b00-e527-11e9-92c9-d6de2f60bd97.png)

**Comment by sammorley-short** [comment]
I have also recently found that TabNine is crashing after a while working in a neovim session and have also found a discrepancy between the version number on my config page (3.2.48-0) vs config file (2.1.22).

@jc00ke Did you manage to find a solution to this in the end?

**Comment by jc00ke** [comment]
@sammorley-short no, I ended up removing `TabNine` :cry:
