### ISSUE TITLE
ultisnips cannot show pop-up menu

### ISSUE THREAD

**Issue by luoleicn** [codota/tabnine-vim#46]
[ultisnips](https://github.com/SirVer/ultisnips) works fine with YouCompleteMe, but cannot show pop-up menu with tabnine

**Comment by lwx5924** [comment]
> [ultisnips](https://github.com/SirVer/ultisnips) works fine with YouCompleteMe, but cannot show pop-up menu with tabnine

@luoleicn do you solve it ?

**Comment by Zackhardtoname** [comment]
Same issue

**Comment by hsequeda** [comment]
Same issue

neovim 5.0
Ubuntu 20.04

**Comment by lianghongji** [comment]
Same issue
Anyone solved it?
