### ISSUE TITLE
[WINDOWS] Error 484 when running :PluginInstall after Vim startup

### ISSUE THREAD

**Issue by ZenithiumDev** [codota/tabnine-vim#48]
OS: Windows 10 x64
Vim version: 8.1

Hi, I've been trying to install TabNine on my machine for half an hour at this point. Everytime I run :PluginInstall on vim startup it shows this error: 

![image](https://user-images.githubusercontent.com/46065852/74083209-ab090680-4a61-11ea-8c3f-d38978048eed.png)

Am I doing something wrong or is it Windows to blame, please explain.
Thank you.

**Comment by GeetHaab** [comment]
Also, Vundle seems to load TabNine as it is in :PluginList but it doesn't work when TabNine commands are typed in the buffer.
