### ISSUE TITLE
Config in vim

### ISSUE THREAD

**Issue by gomes-fdr** [codota/tabnine-vim#51]
When we use install tabnine in vim, we do not have the access inside the editor, things like  `TabNine::<whatever>` does not work.
When I look at the install dir, I saw that we do not have de tabnine.vim in autoload folder, is it correct?

I asked you about that, because I need to access TabNine::config to register me in beta program and I can not do it.

Congrats for your job, regards!

**Comment by sencere** [comment]
I had the same problem. But I think I have a solution for you.

1) make sure, that TabNine is active and you are getting suggestions
2) create a new file and type in 
```
TabNine::config
``` 
A browser should then open and you can configure your tabnine.

Happy Coding.

**Comment by atropos112** [comment]
> 
> 
> I had the same problem. But I think I have a solution for you.
> 
>     1. make sure, that TabNine is active and you are getting suggestions
> 
>     2. create a new file and type in
> 
> 
> ```
> TabNine::config
> ```
> 
> A browser should then open and you can configure your tabnine.
> 
> Happy Coding.

What if you are connected to a headless server , browser opening is not an option. Is there an alternative way ?
