### ISSUE TITLE
CPU load spikes

### ISSUE THREAD

**Issue by hissssst** [codota/tabnine-vim#52]
I am using deoplete-tabnine autocompletion in vim with cloud support.
Sometimes tabnine uses almost 800% of CPU

**Comment by Gandalf-** [comment]
I've seen this just recently on Ubuntu 18.04, `4.15.0-130-generic #134-Ubuntu SMP Tue Jan 5 20:46:26 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux` with latest Tabnine (3.3.46). 

With power saving mode off, Tabnine shows dozens of processes in htop, easily getting up to 1200% CPU on a 16 core system. With power saving mode on, it get's up to 150% CPU but completions don't come through until 2+ seconds later. 

Everything used to work perfectly fine on the same system with Tabnine previous versions, seems like a regression? Are there any logs we can give you?
