### ISSUE TITLE
where should I place the b8373e4b.dms in my laptop?

### ISSUE THREAD

**Issue by fightinggg** [codota/tabnine-vim#56]
I'm in China, When I install tabbing plugin to my vim, and write TabNine::config, I find that I could not download the https://update.tabnine.com/models/b8373e4b
So I copy the url into my Chrome, finaly I download b8373e4.dms successfully
But Where should I place the b8373e4b.dms in my laptop?

**Comment by Eransho** [comment]
Duplicated, see #57
