### ISSUE TITLE
b8373e4b

### ISSUE THREAD

**Issue by fightinggg** [codota/tabnine-vim#57]
When I install tabbing plugin to my vim, and write TabNine::config, I find that I could not download the https://update.tabnine.com/models/b8373e4b
So I copy the url into my Chrome, finaly I download b8373e4.dms successfully
But Where should I place the b8373e4b.dms in my laptop?

**Comment by Eransho** [comment]
Thanks for reporting, we had an issue with tabnine DNS. Can you try again and let us know if it reproduces?
Also, which OS are you using?

**Comment by fightinggg** [comment]
I have try again, but the issue is still here, just like this
<img width="812" alt="截屏2020-04-06下午1 27 08" src="https://user-images.githubusercontent.com/42932982/78525852-e2e6bd00-780a-11ea-9464-1f47c36629f4.png">
the version of OS if 

> Mac OS X 10_15_3  

the version of vim is 

> VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 13 2019 14:45:40)

**Comment by fightinggg** [comment]
> Thanks for reporting, we had an issue with tabnine DNS. Can you try again and let us know if it reproduces?
> Also, which OS are you using?

I have try again, but the issue is still here, just like this
<img width="812" alt="截屏2020-04-06下午1 27 08" src="https://user-images.githubusercontent.com/42932982/78525852-e2e6bd00-780a-11ea-9464-1f47c36629f4.png">
the version of OS if 

> Mac OS X 10_15_3  

the version of vim is 

> VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 13 2019 14:45:40)

**Comment by fightinggg** [comment]
> Thanks for reporting, we had an issue with tabnine DNS. Can you try again and let us know if it reproduces?
> Also, which OS are you using?



> > Thanks for reporting, we had an issue with tabnine DNS. Can you try again and let us know if it reproduces?
> > Also, which OS are you using?
> 
> I have try again, but the issue is still here, just like this
> <img alt="截屏2020-04-06下午1 27 08" width="812" src="https://user-images.githubusercontent.com/42932982/78525852-e2e6bd00-780a-11ea-9464-1f47c36629f4.png">
> the version of OS if
> 
> > Mac OS X 10_15_3
> 
> the version of vim is
> 
> > VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 13 2019 14:45:40)



> Thanks for reporting, we had an issue with tabnine DNS. Can you try again and let us know if it reproduces?
> Also, which OS are you using?



> Thanks for reporting, we had an issue with tabnine DNS. Can you try again and let us know if it reproduces?
> Also, which OS are you using?

**Comment by fightinggg** [comment]
> Thanks for reporting, we had an issue with tabnine DNS. Can you try again and let us know if it reproduces?
> Also, which OS are you using?


I have try again, but the issue is still here, just like this
<img width="812" alt="截屏2020-04-06下午1 27 08" src="https://user-images.githubusercontent.com/42932982/78525852-e2e6bd00-780a-11ea-9464-1f47c36629f4.png">
the version of OS if 

> Mac OS X 10_15_3  

the version of vim is 

> VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 13 2019 14:45:40)

**Comment by fightinggg** [comment]
> Thanks for reporting, we had an issue with tabnine DNS. Can you try again and let us know if it reproduces?
> Also, which OS are you using?


I have try again, but the issue is still here, just like this
<img width="812" alt="截屏2020-04-06下午1 27 08" src="https://user-images.githubusercontent.com/42932982/78525852-e2e6bd00-780a-11ea-9464-1f47c36629f4.png">
the version of OS if 

> Mac OS X 10_15_3  

the version of vim is 

> VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 13 2019 14:45:40)

**Comment by fightinggg** [comment]
> When I install tabbing plugin to my vim, and write TabNine::config, I find that I could not download the https://update.tabnine.com/models/b8373e4b
> So I copy the url into my Chrome, finaly I download b8373e4.dms successfully
> But Where should I place the b8373e4b.dms in my laptop?

test

**Comment by fightinggg** [comment]
yesterday I guess I should place the  b8373e4b.dms in /Users/$(username)/Library/Application Support/TabNine/b8373e4b.tabninemodel
Successfully
