### ISSUE TITLE
configuration to use a key other than <tab> for completion?

### ISSUE THREAD

**Issue by lsankar4033** [codota/tabnine-vim#59]
# Issue Prelude

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x ] I have read and understood YCM's [CONTRIBUTING][cont] document.
- [ x] I have read and understood YCM's [CODE_OF_CONDUCT][code] document.
- [ x] I have read and understood YCM's [README][readme], **especially the
  [Frequently Asked Questions][faq] section.**
- [ x] I have searched YCM's issue tracker to find issues similar to the one I'm
  about to report and couldn't find an answer to my problem. ([Example Google
  search.][search])
- [x ] **I understand this is an open-source project staffed by volunteers and
  that any help I receive is a selfless, heartfelt _gift_ of their free time. I
  know I am not entitled to anything and will be polite and courteous.**
- [ x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

Thank you for adhering to this process! It ensures your issue is resolved
quickly and that neither your nor our time is needlessly wasted.

# Issue Details

> Provide a clear description of the problem, including the following key
> questions:

I use <tab> for something else in vim; wondering if it's straightforward to configure tabnine to use a different key for completion? Thanks in advance!

**Comment by Eransho** [comment]
TabNine vim is based on YouCompleteMe. The available key settings on YCM are applied for TabNine vim as well (for example - https://github.com/ycm-core/YouCompleteMe#the-gycm_key_list_select_completion-option). There is no specific keys configuration for TabNine at the moment
