### ISSUE TITLE
Incorrect binary directory name for 2.8.2

### ISSUE THREAD

**Issue by williamjameshandley** [codota/tabnine-vim#63]
In release 2.8.2, the binaries are still stored in binaries/2.8.1

**Comment by dimacodota** [comment]
This release contains only plugin changes not binary(the binaries are still 2.8.1)
Are you having problems with this release?

**Comment by williamjameshandley** [comment]
Only in that it messes up the [aur](https://aur.archlinux.org/packages/vim-tabnine/) build system, and if you're going to have a patch version number in the directory hierarchy, it should be consistent with the release number.

**Comment by dimacodota** [comment]
Hey @williamjameshandley, thanks for drawing our attention.
can you please elaborate, how did this messed up?
from what I see it pulls the whole extension from '$ {url} / archive / $ {pkgver} .tar.gz' which will pull the extension with its relevant binaries (as soon as pkgver is updated to 2.8.2)

**Comment by dimacodota** [comment]
@williamjameshandley  - I got it, 
`cp -r binaries/${pkgver}/x86_64-unknown-linux-musl/  $installpath/binaries/${pkgver}`
we are managing two separate  release cycles for the plugin and for the binary.
the binary version is determined by the .gitignore !binaries/version field

**Comment by dimacodota** [comment]
can your PKGBUILD be modified to pull the relevant binary version from .gitignore !binaries?

**Comment by williamjameshandley** [comment]
Of course, but this is a hacky solution (and prone to future error). It would be better going forward to have the binaries contained in a consistent directory, or to not have a version number at all (given that there is only one binary directory). Hence the GitHub issue.

**Comment by williamjameshandley** [comment]
Ah, I see! one moment...

**Comment by williamjameshandley** [comment]
Great, that's pushed. Many thanks for your explanation and help @dimacodota

**Comment by dimacodota** [comment]
sure, no problem,
BTW, i would suggest to always pull the latest plugin version 
by calling `https://github.com/codota/tabnine-vim/releases/latest `
