### ISSUE TITLE
How to disable tabnine?

### ISSUE THREAD

**Issue by himat** [codota/tabnine-vim#65]
When I'm on certain servers that have less RAM than my normal dev computer, I'd like to disable tabnine since it uses a lot of RAM.

Is there a way to do this temporarily from within vim without uninstalling the entire plugin?

I'd like to just do `TabNine::disable`

**Comment by amircodota** [comment]
@himat There's no option to completely disable tabnine as it stands.
You can disable tabnine local, which is what uses most of the memory.
You will still get tabnine, suggestions, but ones that are not based on our deep model.

**Comment by himat** [comment]
@amircodota how do I disable tabnine local?

**Comment by amircodota** [comment]
type tabnine::config. A browser window will open with tabnine config.
You have an option there to disable "Deep TabNine Local"
