### ISSUE TITLE
How To Confirm Completion With <CR>?

### ISSUE THREAD

**Issue by nishantc1527** [codota/tabnine-vim#70]
**please complete the following information:**	
 - OS version: [Arch Linux Latest]	
 - Editor version (Output of `vim --version`): v0.5.0-784-gc6ccdda26
 - Programming language: [Java]	
 - TabNine extension version(Type `TabNine::version` in insert mode): 3.2.28
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

**Issue Details:**

Sorry if this is a newb question, but how do I confirm completion? With an editor like Intellij, I just press enter and I get the full output, along with the automatic import. However, with Vim, I select the correct one using <tab> but then I can't figure out how to confirm it. I tried pressing enter, <c-y>, <c-space>, and <c-f>, but none of them worked. I would to know how to confirm completion, and also if possible how to confirm completion using enter (<cr>). Thanks, and sorry to trouble you.

**Comment by amircodota** [comment]
@nishantc1527 When you select a completion it fills the text in the edit buffer. So you can just keep typing and it will be selected.

Hope I'm clear :-)

**Comment by nishantc1527** [comment]
Thanks for clarification
