### ISSUE TITLE
How to make the first completion suggestion auto-selected?

### ISSUE THREAD

**Issue by zhuo1angT** [codota/tabnine-vim#74]
**please complete the following information:**	
 - OS version: Arch Linux	
 - Editor version (Output of `vim --version`): 8.2
 - Programming language: All language
 - TabNine extension version(Type `TabNine::version` in insert mode):
 3.3.33
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

**Issue Details:**
The plugin is really awesome and I love it. But the behavior a little bit different from the one in the `VS Code Extension`, which is: the first suggestion is not auto-selected, and I have to use the arrow keys manually to do it. Is' there a way to config it?

thanks!

**Comment by avnerbarr** [comment]
@dimacodota
