### ISSUE TITLE
filetype blacklist is being ignored

### ISSUE THREAD

**Issue by michaelb** [codota/tabnine-vim#75]
- OS version: Archlinux, 5.11.4 (basically irrelevant, should affect every OS and distro)
- Editor version: Neovim 0.5 (also irrelevant, will affect vim and neovim of any version)
- Programming language: all
- Tabnine extension version: 3.3.96

**Issue Details:**
Tabnine does not respect the blacklist, be it from the g:ycm_filetype_blacklist vim variable, or even the default config in third_party/ymcd/ycmd/default_settings.json

There is an early 'return 1' in a function that short-circuits the logic and basically allow completion for any filetype. Though, removing it does not seem to cause any kind of issue [on my system, should be tested elsewhere just in case]. Git blames @zxqfl , so I might just tag him, but the commit message is unrelated. Maybe a test config was pushed? 

I cannot stress how annoying it is to have undesired completion in some buffers, such as the [telescope](https://github.com/nvim-telescope/telescope.nvim) prompt, but i guess others similar things (fzf, floating windows).

See my pull request for the fix

**Comment by avnerbarr** [comment]
@dimacodota

**Comment by michaelb** [comment]
It was some time ago, but it was on purpose. I though that markdown is most often written as part of a project, and code-aware prose completion wasn't so bad (you don't have any lsp feature ofc).

But anyway, with this PR the 

`let g:ycm_blacklist_filetype` key should be respected

(All -read: too much- info about that is available in `:help youcompleteme`)

**Comment by hoschi** [comment]
`let g:ycm_filetype_blacklist` works indeed with the PR, I just wondered, because the docs still say markdown is ignored by default:
https://github.com/michaelb/tabnine-vim/blob/master/doc/youcompleteme.txt#L2413

**Comment by michaelb** [comment]
whoops you're right. I'll update the docs (selfish me wants to keep markdown completion)
