### ISSUE TITLE
I want to work with complete-nvim and tabnine at the same time

### ISSUE THREAD

**Issue by Johan-Palacios** [codota/tabnine-vim#85]
- OS version: WSL 1/Ubuntu
 - Editor version Neovim 0.5
 - Programming language: Python
 

**Issue Details:**
When I installed the plugin and i tried to use the plugin this cause a bug with the LSP and tabnine, and the nvim not works, I want, see a posible solution for the plugin, because i want to use this tools at the same time

gz#3933

**Comment by maya-tabnine** [comment]
Hi, after adding the tabnine plugin to your vimrc, is the plugin not suggesting completions? or did the nvim freeze?
Do you have any errors or logs to share?

**Comment by Johan-Palacios** [comment]
Yes tabnine don't do autosuggestion and later of that Nvim freeze, and I can't work in my code

**Comment by maya-tabnine** [comment]
For some reason, In some cases Tabnine has issues loading.
When installing using the brew formula only, it works fine. Try reinstalling nvim using 'brew install vim'.
See these GitHub issues for reference: https://github.com/codota/tabnine-vim/issues/41#issuecomment-742814083 https://github.com/codota/tabnine-vim/issues/79

**Comment by Johan-Palacios** [comment]
Thanks now it works
