### ISSUE TITLE
Junk characters in multiline suggestions

### ISSUE THREAD

**Issue by iBug** [codota/tabnine-vim#89]
### System Information

 - OS version: Ubuntu 20.04.2 LTS
 - Editor version (Output of `vim --version`): VIM 8.1 (Ubuntu stock package `vim`)
 - Programming language: [e.g. js, ts, c++]: Python and Go
 - TabNine extension version: 3.5.35

Attached file: [tabnine.log](https://github.com/codota/tabnine-vim/files/6936071/tabnine.log)

### Details

TabNine produces junk characters (namely `^@`, the NUL byte) in candidates for multiline suggestions.

![image](https://user-images.githubusercontent.com/7273074/128293821-1f71f41e-9df1-4db0-81f2-f93758aa2e39.png)

When a candidate with junk characters is selected and deleted char-by-char back to the junk position, something else shows up.

![image](https://user-images.githubusercontent.com/7273074/128293857-49b4c52b-e61b-4591-9ce8-a973bfbe2961.png)

gz#4752

**Comment by iBug** [comment]
@bilucodota Hello, why is this closed without any context?

**Comment by bilucodota** [comment]
Hi @iBug, thanks for reaching out!
`tabnine-vim` had a a major release yesterday. Basically we've taken the latest YCM and re-implemented Tabnine on top of it. The code was moved to  https://github.com/tabnine/YouCompleteMe (feel free to update) so I had to close all the issues on this repo.

I see your issue still reproduces on the new implementation - I will look into it. Will keep you updated.

**Comment by bilucodota** [comment]
Hi @iBug 

I pushed a partial fix
https://github.com/tabnine/YouCompleteMe/commit/cd9c925130299064ca8d60ed41217d066ca8dd7c
There's a known issue when accepting completion with `<CR>` but other than that it should work
