### ISSUE TITLE
404 Client Error: Not Found for url: http://127.0.0.1:53871/filter_and_sort_candidates

### ISSUE THREAD

**Issue by kingdido999** [codota/tabnine-vim#9]
When editing a JavaScript file in insert mode, vim shows this error message every time I type `.`:

```
404 Client Error: Not Found for url: http://127.0.0.1:53871/filter_and_sort_candidates
```

I haven't found this error when working with files in other languages, but I'm not sure if it's just happening to js files.

I installed this plugin through Vundle. My vim version is `8.0`.

**Comment by anowlcalledjosh** [comment]
I run into this very frequently when editing Python files (especially when entering a dot after a number).

**Comment by GenaBitu** [comment]
PHP as well...

**Comment by anowlcalledjosh** [comment]
This also happens every time I insert an `@` in a Python file, so decorators are impossible to autocomplete. (There's also often some `function: syntax error...` spam (#6) if I then insert an underscore `_`.)

**Comment by zxqfl** [comment]
I was not able to reproduce this issue on my own machine. It may be the result of your YCM configuration -- if you can post your configuration, I may be able to reproduce the issue. Nonetheless it seems to be related to `OmniCompleter`, so I made my best effort to fix it by looking around related code. Let me know if it works.

**Comment by kingdido999** [comment]
I haven't edited any configuration for YCM, so I'm not sure about what configuration I need to look into...As a side note, probably a workaround as well, the error no longer occurs after I switch to [Neovim](https://neovim.io/).

**Comment by GenaBitu** [comment]
I've been using neovim all along...

**Comment by zxqfl** [comment]
Can you confirm that you updated to the latest version of tabnine-vim and are still having this issue?

**Comment by GenaBitu** [comment]
Unless there is a specific step needed that is different from other vim plugins (I am using plug for plugin management), yes, I have the latest version as of now.
