### ISSUE TITLE
More completion engines

### ISSUE THREAD

**Issue by brandoncc** [codota/tabnine-vim#93]
Hello,

Thanks for this awesome tool!

I just wanted to make your team aware of more vim (neovim specifically) completion engine plugins:

nvim-compe: https://github.com/tzachar/compe-tabnine
nvim-cmp: https://github.com/tzachar/cmp-tabnine

gz#5929

**Comment by bilucodota** [comment]
Thanks @brandoncc ! will definitely add these

**Comment by yzlin** [comment]
@bilucodota please add support for https://github.com/nvim-lua/completion-nvim too

**Comment by bilucodota** [comment]
Added. Thanks!
