### ISSUE TITLE
Slow on installation or upgrade

### ISSUE THREAD

**Issue by XuehaiPan** [codota/tabnine-vim#99]
**please complete the following information:**	
 - OS version: Ubuntu 20.04 LTS	
 - Editor version (Output of `vim --version`): vim 8.2
 - Programming language: [e.g. js, ts, c++] Python
 - TabNine extension version(Type `TabNine::version` in insert mode): 3.7.25
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

**Issue Details:**

In this repo, we add binaries for Tabnine Engines into Git histories. This makes the Git repo extremely large and takes too long to install or upgrade. The `.git` folder grows as we update the binary files.

In the screenshot below:

![Screenshot-tabnine](https://user-images.githubusercontent.com/16078332/139540101-5b7d39f8-0362-4476-ad0c-002551548050.png)

It takes 198 seconds to get a full clone (requires 1018M disk space) or 53 seconds to get a fresh shallow clone (requires 506M disk space). Using `vim-plug`, sometimes, it takes more than 5 minutes to upgrade Tabnine on a shallow clone.

I think we should provide a separate method to install the binaries rather than put the binaries to Git histories.

**Comment by bilucodota** [comment]
Hi @XuehaiPan 
Thanks for reaching out!
Check out our new `ycm` fork. 

https://github.com/tabnine/YouCompleteMe

Which does not bundle Tabnine binaries. 
Your feedback is highly appreciated.
